docs/vitest/entorno-de-prueba.md
package-lock.json
package.json

refactor: Review test environment

refactor: Review test environment

---

docs/vitest/un-ejemplo-asincrono.md

feat: Review An Asynchronous Example

feat: Review An Asynchronous Example

---

docs/vitest/funciones-simuladas.md
package-lock.json

feat: Review Mock Functions

---

docs/vitest/simulaciones.md

feat: Mocking

---

docs/.vitepress/config.js
docs/cypress-vtc/inicio-rapido.md
docs/cypress-vtc/probando-componentes.md

feat: Testing Vue Components

---

docs/.vitepress/config.js
docs/cypress-vtc/pobando-componentes-con-eventos-emitidos.md

feat: Testing Vue Components with Emitted Events

feat: Testing Vue Components with Emitted Events

---

docs/.vitepress/config.js
docs/cypress-vtc/componentes-con-eventos-emitidos.md
docs/cypress-vtc/componentes-con-slots.md
docs/cypress-vtc/prueba-de-componentes.md

feat: Start Testing Components with Slots

feat: Start Testing Components with Slots

---

docs/cypress-vtc/componentes-con-slots.md

feat: Continuing with Testing Components Slots

feat: Continuing with Testing Components Slots

---

docs/cypress-vtc/componentes-con-slots.md

feat: Named Slots

---

docs/.vitepress/config.js
docs/cypress-overview/diferencias-clave.md

feat: Key Differences

---

docs/.vitepress/config.js
docs/todo-con-pinia/store.md

feat: Code for todo with pinia - the store

feat: Code for todo with pinia - the store

---

docs/.vitepress/config.js
docs/todo-con-pinia/crear-una-nueva-tarea.md
docs/todo-con-pinia/definiendo-la-tienda.md
docs/todo-con-pinia/dev-app-con-tdd.md

feat: Define store

---

docs/todo-con-pinia/definiendo-la-tienda.md

fix: Define store

---

docs/.vitepress/config.js
docs/todo-con-pinia/mundo-real.md

feat: Create New Task2

---

docs/todo-con-pinia/actualizar-tarea.md
docs/todo-con-pinia/consultar-tareas.md
docs/todo-con-pinia/crear-nueva-tarea.md
docs/todo-con-pinia/eliminar-tarea.md

feat: Add show test running

---

docs/todo-con-pinia/consultar-tareas.md
docs/todo-con-pinia/crear-nueva-tarea.md

feat: Consult tasks

---

docs/todo-con-pinia/consultar-tareas.md

fix: Consult tasks

---

docs/todo-con-pinia/eliminar-tarea.md

feat: Remove task

---

docs/.vitepress/config.js
docs/todo-con-pinia/actualizar-tarea.md
docs/todo-con-pinia/codigo-completo.md
docs/todo-con-pinia/mundo-real.md

feat: Update task and full code

feat: Update task and full code

---

docs/todo-con-pinia/actualizar-tarea.md
docs/todo-con-pinia/codigo-completo.md
docs/todo-con-pinia/consultar-tareas.md
docs/todo-con-pinia/crear-nueva-tarea.md
docs/todo-con-pinia/eliminar-tarea.md

style: Add files name

---

docs/.vitepress/config.js
docs/todo-con-pinia/crud-todo-list.md

style: Rename TODO-List

---

docs/.vitepress/config.js

fix: JSON format

---

docs/vtl/ddp/patrones-para-probar-propiedades.md

fix: Add a validator

---

docs/vtl/ddp/emitir-eventos.md

docs: Emitting Events - Starting Simple

docs: Emitting Events - Starting Simple

---

docs/.vitepress/config.js
docs/vtl/ddp/emitir-eventos.md
docs/vtl/ddp/escribir-formularios-comprobables.md

docs: Finishing chapter 4

---

docs/vtl/ddp/escribir-formularios-comprobables.md

docs: Building validateMeasurement with isBetween

docs: Building validateMeasurement with isBetween

---

docs/vtl/ddp/escribir-formularios-comprobables.md

docs: The Form Object and Full Form Validation

docs: The Form Object and Full Form Validation

---

docs/vtl/ddp/http-y-api-requests.md

docs: HTTP & API Reqs; The Login Component; Starting Simple

docs: HTTP & API Reqs; The Login Component; Starting Simple

---

docs/.vitepress/cache/deps/_metadata.json
docs/vth/vuex-mutaciones.md

style: Put sh file type

---

docs/.vitepress/config.ts
docs/index.md

fix: Link paths

---

docs/vitest/simulaciones.md

fix: Automocking algorithm

---

docs/.vitepress/configBack.ts
package-lock.json
package.json

feat: Update vitepress version

feat: Update vitepress version
